### ISSUE TITLE
UXv reporting status to control station

### ISSUE THREAD

**Issue by ntartania** [NMAI-lab/SAVI#143]
This is a request from Cohort: the UxV should report their status periodically (ideally 10Hz) over the wifi.
information that must be included (all as integers):

- x,y,z in meters
- pitch, roll, yaw in degrees (we give neutral values of 90 for all 3)
- Azimuth in degrees relative to north which is 0 increasing clockwise to 359
- Speed in meters/s
- Health is 0-100%
- Communication Strength is 0-100%
- Might want to add a single measure of sensor health in the range 0-100%

We need to figure out the exact semantics of health / communication strength / sensor health.
Ideally reporting frequency is 10Hz. I believe we should do this directly in Java (not agentspeak), on the agent side using perceived values. Alternative could be an internal action.

**Comment by pgavigan** [comment]
I have added a plan to the UxV behaviours that partially addresses this. If the UxV is provided an "achieve" message with the goal of sendTelemetry all UxVs will respond with .broadcast(tell, notifyPosition(X,Y,Z,TP)) and .broadcast(tell, notifyVelocity(BEARING,PITCH,SPEED,TV)). TP and TV represent the time that each of those data points were perceived.

These are the only perceptions that the agent currently received that are relevant to the requested telemetry list. For now, I suggest that we limit our telemetry to this list as further telemetry would require enhancements that I believe are currently out of the project scope for this stage.

I recommend that the control station send these achieve messages at regular intervals in order to trigger this plan.

**Comment by pgavigan** [comment]
Addressed by PR #149
